# Generated by Django 6.0.4 on 2026-05-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_businessapplication_systemsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='form_type',
            field=models.CharField(db_index=True, default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='ipm_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inspection',
            name='nccg_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
