# Generated by Django 6.0.4 on 2026-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_decline_reason_inspection_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='people_on_ground',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
